### ISSUE TITLE
Add support for Map, Tuple1, ByteArray and Any

### ISSUE THREAD

**Issue by mpapierski** [Zondax/ledger-casper#101]
Here's the PR: https://github.com/casper-ecosystem/casper-deploy-generator/pull/66 currently in the review; although `manual.json` file is perfectly usable in this branch.

This PR adds a few more test cases for the following types:

- Map
- Tuple1
- ByteArray
- Any

When this is done, it should close #100 as well 

:link: [zboto Link](https://app.clickup.com/t/86938yr40)

**Comment by ftheirs** [comment]
Implemented here: https://github.com/Zondax/ledger-casper/pull/103
