### ISSUE TITLE
Refactor Ledger UI

### ISSUE THREAD

**Issue by goral09** [Zondax/ledger-casper#43]
https://github.com/casper-ecosystem/casper-deploy-generator/pull/32 has made a couple of notable changes to what is being displayed on the ledger device. We need to reflect that in the Casper Ledger app. 

Changelist:
1. Renames `source` (from deploy header) to `account`.
2. Renames `amount` on payment view to `fee`.
3. Removes `payment system` pane altogether – when the system/built-in payment is used, we don't display that in the Ledger device. Equivalent mechanism is implemented in many other blockchains (including Ethereum) so, for the sake of simplicity and familiarity, we will not display this pane anymore.
4. Adds `Txn hash` pane to Ledger views. That is a hash of the deploy/txn being signed.
5. Do not display `Auction: Delegate/Undelegate` ledger pane – those are displayed in `Type: *` pane.
6. Do not display `Execution: native transfer` ledger pane – this is displayed as `Type: token transfer`.

https://github.com/casper-ecosystem/casper-deploy-generator/pull/32 contains updated test vectors.

**Comment by leongb** [comment]
Closed with https://github.com/Zondax/ledger-casper/pull/44
