### ISSUE TITLE
Casper app not working anymore

### ISSUE THREAD

**Issue by Trader1976** [Zondax/ledger-casper#62]
Seems Casper app stopped working after mainnet upgrade couple days ago. Trying to sign in in cspr.live with ledger nano jumps back to front page.

**Comment by jleni** [comment]
Could you please confirm that Ledger Live is closed?

Ledger Live is known to trigger a close app if it is left open in the manager mode.

**Comment by Trader1976** [comment]
Hi,
Yes, it was closed. I've been trying with 2 computers, 3 browsers and even cell phone.Nothing works. 



-----Original Message-----

**Comment by Trader1976** [comment]
Hi,Here is some more information.
I've noticed that if I clear cookies cache, I'm able to click connect button and thenconnect with ledger app. It then asks me which wallet to open and when I clickmy wallet, it goes back to front page.
Next time if I click sign in and then connect, it just goes back to front page.
So, if I empty cookies cache, then it goes further but I'm still not ableto login.
This problem started about 2 days ago and in telegram they told me thatthere was mainnet upgrade 2 days ago. 
Cheers,Timo


-----Original Message-----

**Comment by jleni** [comment]
> cspr.live with ledger nano jumps back to front page.

> Next time if I click sign in and then connect, it just goes back to front page.

Oh, I understand now. You meant that the **website** jumps to the frontpage? Not that the device itself changes or goes to main menu. I see.

This is very likely an issue at the website level that is not related to the Ledger app itself but to the integration.

We will contact the cspt.live team and inform them about this issue in the website. Thanks!

**Comment by piotrwitek** [comment]
This was a minor state management issue after upgrading wallet synchronization across multiple browser windows & tabs. We have already fixed the issue and we'll publish it in the next cspr.live release.

**Comment by piotrwitek** [comment]
Just wanted to let you all know that the hotfix v1.6.2 with Ledger fix just landed on production.
